name: Auto Update AI News

on:
  schedule:
    # 毎日朝7時(JST) = 前日22時(UTC)に実行
    - cron: '0 22 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install feedparser pyyaml deep-translator==1.11.4
    
    - name: Set environment variables
      run: |
        echo "TRANSLATE_TO_JA=1" >> $GITHUB_ENV
        echo "TRANSLATE_ENGINE=google" >> $GITHUB_ENV
        echo "HOURS_LOOKBACK=24" >> $GITHUB_ENV
        echo "MAX_ITEMS_PER_CATEGORY=20" >> $GITHUB_ENV
        echo "X_POSTS_CSV=https://docs.google.com/spreadsheets/d/1uuLKCLIJw--a1vCcO6UGxSpBiLTtN8uGl2cdMb6wcfg/export?format=csv&gid=0" >> $GITHUB_ENV
    
    - name: Update news detail page
      run: python build.py
      continue-on-error: true
    
    - name: Generate dashboard
      run: python generate_comprehensive_dashboard.py
      continue-on-error: true
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: Auto update AI news [skip ci]"
        git push
