name: Daily build

on:
  schedule:
    - cron: '0 22 * * *'   # 07:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      HOURS_LOOKBACK: '24'
      MAX_ITEMS_PER_CATEGORY: '8'
      TRANSLATE_TO_JA: '1'           # ← 要約を日本語化
      DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}  # ← Secrets に登録が必要
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install feedparser pyyaml deepl

      - name: Build HTML
        run: python build.py

      - name: Commit and push (including cache)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update index.html & cache [skip ci]" || echo "no changes"
          git push
