name: Daily build (JA summaries fixed)
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * *"   # 07:00 JST
  workflow_dispatch:
permissions: { contents: write }
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      HOURS_LOOKBACK: "24"
      MAX_ITEMS_PER_CATEGORY: "8"
      TRANSLATE_TO_JA: "1"
      TRANSLATE_ENGINE: "google"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install feedparser pyyaml deep-translator==1.11.4
      - name: Build HTML
        run: python build.py
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update index.html [skip ci]" || echo "no changes"
          git push
