name: Daily build (JA summaries fixed)
on:
  schedule:
    - cron: "0 22 * * *"   # 07:00 JST (daily automatic update)
  workflow_dispatch:        # Manual execution only
permissions: 
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      HOURS_LOOKBACK: "24"
      MAX_ITEMS_PER_CATEGORY: "8"
      TRANSLATE_TO_JA: "1"
      TRANSLATE_ENGINE: "google"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install feedparser pyyaml deep-translator==1.11.4 google-generativeai python-dotenv
      - name: Build HTML and Daily Report
        timeout-minutes: 10
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          timeout 420 python build.py || echo "Build timeout, using emergency build"
          timeout 120 python generate_fixed_dashboard.py || echo "Fixed dashboard timeout, using fallback"
          if [ -f "fixed_dashboard_*.html" ]; then cp fixed_dashboard_*.html index.html; fi
          timeout 120 python generate_comprehensive_dashboard.py || echo "Dashboard timeout, skipping"
          timeout 300 python generate_daily_business_report.py || echo "Daily report timeout, skipping"
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update site content [skip ci]" || echo "no changes"
          git push
