name: Daily build

on:
  schedule:
    - cron: '0 22 * * *'   # 07:00 JST（UTC 22:00）
  workflow_dispatch:

# ★ これがないと GITHUB_TOKEN で commit/push できません
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser pyyaml

      - name: Build HTML
        run: python build.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "chore: update index.html [skip ci]" || echo "no changes"
          git push
