name: Deploy AI News to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 7:00 JST (22:00 UTC)
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt || pip install feedparser pyyaml deep-translator==1.11.4 beautifulsoup4 requests google-generativeai>=0.3.0
        
    - name: Set environment variables
      run: |
        echo "TRANSLATE_TO_JA=1" >> $GITHUB_ENV
        echo "TRANSLATE_ENGINE=google" >> $GITHUB_ENV
        echo "HOURS_LOOKBACK=24" >> $GITHUB_ENV
        echo "MAX_ITEMS_PER_CATEGORY=25" >> $GITHUB_ENV
        
    - name: Build AI News Site
      timeout-minutes: 10
      run: |
        echo "🔨 Building AI News site with enhanced ranking..."
        python build_simple_ranking.py
        
        echo "📊 Verifying build output..."
        if [ -f "index.html" ]; then
          file_size=$(stat -c%s index.html)
          echo "✅ index.html generated ($file_size bytes)"
          
          if [ "$file_size" -gt 10000 ]; then
            echo "✅ Build verification passed"
          else
            echo "⚠️ Build file seems small but continuing..."
          fi
        else
          echo "❌ index.html not generated!"
          exit 1
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      
    - name: Display results
      run: |
        echo "🎉 Deployment completed!"
        echo "🌐 Site URL: https://awano27.github.io/daily-ai-news-pages/"
        echo "📅 Expected: Current date with enhanced features"
        echo "🖱️ Expected: Working tab functionality"