name: Minimal Build Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Test build
        run: |
          echo "🧪 Minimal build test"
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          
          # 最小限のHTMLを生成
          cat > test_build.html << 'EOF'
<!DOCTYPE html>
<html>
<head><title>Build Test</title></head>
<body>
<h1>Build Test Success</h1>
<p>Generated at: $(date)</p>
</body>
</html>
EOF
          
          echo "✅ Test HTML created"
          
      - name: Deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test_build.html || true
          git commit -m "🧪 Minimal build test $(date)" || echo "No changes"
          git push || echo "Push failed"
