name: Simple Daily Build with X Posts
on:
  push:
    branches: [ main, gh-pages ]
  schedule:
    - cron: "0 22 * * *"   # 07:00 JST
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          pip install feedparser pyyaml deep-translator requests beautifulsoup4
          
      - name: Build site with X posts
        env:
          TRANSLATE_TO_JA: "1"
          TRANSLATE_ENGINE: "google"
          HOURS_LOOKBACK: "24"
          MAX_ITEMS_PER_CATEGORY: "8"
          X_POSTS_CSV: "https://docs.google.com/spreadsheets/d/1uuLKCLIJw--a1vCcO6UGxSpBiLTtN8uGl2cdMb6wcfg/export?format=csv&gid=0"
        run: |
          echo "Building site with X posts..."
          python build.py || echo "Build completed with warnings"
          
      - name: Verify X posts in HTML
        run: |
          if grep -q "X / SNS" index.html; then
            echo "✅ X posts found in index.html"
            echo "📊 X post URLs:"
            grep -o 'href="https://x\.com/[^"]*"' index.html | head -5
          else
            echo "⚠️ X posts not found in index.html"
          fi
          
      - name: Debug X posts processing
        env:
          X_POSTS_CSV: "https://docs.google.com/spreadsheets/d/1uuLKCLIJw--a1vCcO6UGxSpBiLTtN8uGl2cdMb6wcfg/export?format=csv&gid=0"
        run: |
          echo "🔍 Debugging X posts CSV structure..."
          curl -s "$X_POSTS_CSV" | head -3
          echo ""
          echo "🔗 Looking for X URLs in CSV..."
          curl -s "$X_POSTS_CSV" | grep -o 'https://[^,]*x\.com[^,]*' | head -5 || echo "No x.com URLs found in top rows"
          
      - name: Commit and deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *.html style.css || true
          git commit -m "🤖 Daily update with X posts - $(date +'%Y-%m-%d %H:%M JST')" || echo "No changes"
          git push origin gh-pages
          
      - name: Summary
        run: |
          echo "✅ Build complete!"
          echo "Site: https://awano27.github.io/daily-ai-news/"